#$ -S /bin/bash
#$ -N merge_remove-primers_quality-filter_uniques_find-joint
#$ -o /workdir/users/pd378/oilPCR/all_16s_for_paper/read_process_out.txt
#$ -e /workdir/users/pd378/oilPCR/all_16s_for_paper/read_process_err.txt
#$ -wd /workdir/users/pd378/oilPCR/all_16s_for_paper #Your working directory
#$ -pe parenv 1
#$ -l h_vmem=30G
#$ -t 1-3
#$ -q short.q@cbsubrito

#export usearch
export PATH=/programs/usearch11.0.667:$PATH
##Set dirs
WRK=/workdir/users/pd378/oilPCR/all_16s_for_paper
##Path to the list of file names
LIST=$WRK/file_lists/all_filelist.txt

####MERGE VARIABLES###
MERGE_IN=$WRK/rawdata ## raw reads folder
MERGE_OUT=$WRK/s1_merge_reads ##where to put the merged reads
MIN_MERGE=283       #cutoff for minimum merge length
MAX_MERGE=293       #cutoff for maximum merge length 
MAX_DIFFS=20       #How many difference are allowed for overlap
PCTID=85 
####PRIMER STRIP VARIABLES####  set variables in call
PSTRIP_OUT=$WRK/s2_strip_primers #output for the stripped reads

####QUALITY FILTER VARIABLES####
QFILTER_OUT=$WRK/s3_quality_filter
MAX_ERROR=1.0
####FILTER UNIQUES VARIABLES####
UNIQUE_OUT=$WRK/s4_filter_uniques

####Cluster OTUs########
OTU_OUT=$WRK/s5_cluster_uniques






##Make the design file
        DESIGN=$(sed -n "${SGE_TASK_ID}p" $LIST)
        NAME=`basename "$DESIGN"`

##############RUN USEARCH MERGE PAIRS ####################
mkdir $MERGE_OUT
mkdir $MERGE_OUT/stats
FORWARD=$MERGE_IN/${NAME}_R1.fastq
REVERSE=$MERGE_IN/${NAME}_R2.fastq
M_OUT=$MERGE_OUT/${NAME}_merged.fq
M_STATS=$MERGE_OUT/stats/${NAME}.txt

usearch -fastq_mergepairs $FORWARD -reverse $REVERSE -fastq_maxdiffs $MAX_DIFFS -fastq_pctid $PCTID -fastq_minmergelen $MIN_MERGE -fastq_maxmergelen $MAX_MERGE -fastqout $M_OUT 2> $M_STATS

echo $NAME merge complete

############ RUN PRIMER TRUNCATE #####################
mkdir $PSTRIP_OUT
mkdir $PSTRIP_OUT/stats
P_OUT=$PSTRIP_OUT/${NAME}_stripped.fq
P_STATS=$PSTRIP_OUT/stats/${NAME}.txt

usearch -fastx_truncate $M_OUT -stripleft 18 -stripright 20 -fastqout $P_OUT 2> $P_STATS

echo $NAME primer strip complete

########### RUN QUALITY FILTER ###################
mkdir $QFILTER_OUT
mkdir $QFILTER_OUT/stats
Q_OUT=$QFILTER_OUT/${NAME}_filtered.fa
Q_STATS=$QFILTER_OUT/stats/${NAME}.txt

usearch -fastq_filter $P_OUT -fastq_maxee $MAX_ERROR -fastaout $Q_OUT 2> $Q_STATS

echo $NAME quality filter compete

########### RUN FILTER UNIQUES ##################
mkdir $UNIQUE_OUT
mkdir $UNIQUE_OUT/stats
U_OUT=$UNIQUE_OUT/${NAME}_unique.fa
U_STATS=$UNIQUE_OUT/stats/${NAME}.txt

usearch -fastx_uniques $Q_OUT -fastaout $U_OUT -relabel Uniq -sizeout 2> $U_STATS

echo $NAME filter uniques complete



############# Run Cluster OTUs ##############


usearch -cluster_otus $SORTED_READS -otus $OTU_OUT -relabel otu -uparseout $PARSED -minsize 1 2> $STATS





